#!/bin/bash

config_file=$1
tmp_button_file=/tmp/retroarch_buttons.tmp

rm -f $tmp_button_file

if [[ ! -e $config_file.bak ]]; then
	cp $config_file $config_file.bak
fi	

cp $config_file.bak $config_file

./retroarch-joyconfig >> $tmp_button_file

for pad in {1..3}; do
	player=`expr $pad + 1`
	cat $tmp_button_file | eval "sed 's/player1/player${player}/'" | eval "sed 's/joypad_index = \"0\"/joypad_index = \"${pad}\"/'" >> $config_file
done
